/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zkteco_autk_utils_ImageUtil */

#ifndef _Included_com_zkteco_autk_utils_ImageUtil
#define _Included_com_zkteco_autk_utils_ImageUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zkteco_autk_utils_ImageUtil
 * Method:    absdiff
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zkteco_autk_utils_ImageUtil_absdiff
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
